name: Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests

    steps:
      - uses: actions/checkout@v2
      - name: Install composer deps
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: composer test
